composer:
    "spryker/message-broker": "^1.0.0"
    "spryker/message-broker-aws": "^1.0.0"
plugins:
    - "\\{projectNamespace}\\Zed\\Console\\ConsoleDependencyProvider":
        method: "getConsoleCommands"
        plugins:
          - "\\Spryker\\Zed\\MessageBroker\\Communication\\Plugin\\Console\\MessageBrokerWorkerConsole"

    - "\\{projectNamespace}\\Zed\\MessageBroker\\MessageBrokerDependencyProvider":
        method: "getMessageSenderPlugins"
        plugins:
          - "\\Spryker\\Zed\\MessageBrokerAws\\Communication\\Plugin\\MessageBroker\\AwsSqsMessageSenderPlugin"
          - "\\Spryker\\Zed\\MessageBrokerAws\\Communication\\Plugin\\MessageBroker\\HttpMessageSenderPlugin"

    - "\\{projectNamespace}\\Zed\\MessageBroker\\MessageBrokerDependencyProvider":
        method: "getMessageReceiverPlugins"
        plugins:
          - "\\Spryker\\Zed\\MessageBrokerAws\\Communication\\Plugin\\MessageBroker\\AwsSqsMessageReceiverPlugin"

    - "\\{projectNamespace}\\Zed\\MessageBroker\\MessageBrokerDependencyProvider":
        method: "getMessageAttributeProviderPlugins"
        plugins:
          - "\\Spryker\\Zed\\MessageBroker\\Communication\\Plugin\\MessageBroker\\AppIdentifierMessageAttributeProviderPlugin"
          - "\\Spryker\\Zed\\MessageBroker\\Communication\\Plugin\\MessageBroker\\CorrelationIdMessageAttributeProviderPlugin"
          - "\\Spryker\\Zed\\MessageBroker\\Communication\\Plugin\\MessageBroker\\TenantIdentifierMessageAttributeProviderPlugin"
          - "\\Spryker\\Zed\\MessageBroker\\Communication\\Plugin\\MessageBroker\\TimestampMessageAttributeProviderPlugin"

env:
    - "AOP_MESSAGE_TO_CHANNEL_MAP"
    - "AOP_CHANNEL_TO_TRANSPORT_MAP"
    - "AOP_CHANNEL_TO_SENDER_TRANSPORT_MAP"
    - "AOP_CHANNEL_TO_RECEIVER_TRANSPORT_MAP"
