asyncapi: 2.2.0
info:
    title: 'Test File'
    version: 0.1.0
components:
    schemas:
        headers:
            type: object
            required:
                - timestamp
                - store
                - correlationId
            properties:
                timestamp:
                    type: integer
                    description: 'Timestamp when this message was created (microtime).'
                store:
                    type: string
                    description: 'Store name that triggered the event.'
                appIdentifier:
                    type: string
                    description: 'Identifier of the app for the triggered event.'
                correlationId:
                    type: string
                    description: 'Identifier of the current process.'
        message:
            type: object
            properties:
                firstname:
                    type: string
            required:
                - firstname
        message2:
            type: object
            properties:
                firstname:
                    type: string
            required:
                - firstname
    messages:
        message:
            name: message
            summary: ''
            payload:
                $ref: '#/components/schemas/message'
        message2:
            name: message
            summary: ''
            payload:
                $ref: '#/components/schemas/message2'
